server:
  port: 8094
  servlet:
    context-path: /community   
spring:
  application:
    name: ui-community-service 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/